# .github/workflows/test-aind-behavior-framework.yml
name: Runs integration tests between Bonsai, Python and jsonschema

on:
  workflow_call:
    inputs:
      bonsai-working-directory:
        type: string
        description: 'The working directory for the bonsai setup'
        required: false
        default: 'bonsai'
      python-version-path:
        type: string
        description: 'The path to the python version file'
        required: false
        default: ".python-version"
      run-coverage:
        type: boolean
        description: 'Whether to run test coverage'
        required: false
        default: false
      run-schema:
        type: boolean
        description: 'Whether to run schema regeneration'
        required: false
        default: false

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Setup Bonsai environment
        working-directory: ${{ inputs.bonsai-working-directory }}
        run: .\Setup.ps1

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Check if uv.lock is up-to-date
        run: uv lock --check

      - name: Install python dependencies
        run: uv sync --extra dev

      - name: Run python unit tests
        shell: bash
        run: |
          if [ "${{ inputs.run-coverage }}" = "true" ]; then
            uv run -m coverage run -m unittest
            uv run -m coverage report
          else
            uv run -m unittest
          fi

      - name: Regenerate schemas
        if: ${{ inputs.run-schema }}
        run: uv run regenerate

      - name: Check for uncommitted changes
        run: |
          git config --global core.safecrlf false
          git diff --exit-code || (echo "Untracked changes found" && exit 1)
